version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: 'app.log'  # Nome do arquivo de log
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed

loggers:
  app_logger:
    level: INFO
    handlers: [file_handler, console_handler]
    propagate: False

root:
  level: WARNING
  handlers: [console_handler]
